
package From;

import ChiaSeKhoa.ChiSeKhoa;
import ChiaSeKhoa.ChiaSeKhoaDAO;
import des.DES;
import ChiaSeKhoa.DuocChon;
import ChiaSeKhoa.DuocChonDAO;
import des.Khoa;
import ChiaSeKhoa.dsADAO;
import java.awt.Desktop;
import java.io.BufferedOutputStream;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.lang.String;
import javax.swing.filechooser.FileNameExtensionFilter;

public class From extends javax.swing.JFrame {
    int MaHoaHayGiaiMa = 1;
    DES MaHoaDES64;
    Khoa Khoa;
    ArrayList<Long> ds=new ArrayList<>();
    ArrayList<Long> dsg=new ArrayList<>();
    ArrayList<DuocChon> dsdc=new ArrayList<>();
    /**
     * Creates new form From
     */
    public static boolean KtSNT(long n) {
        // so nguyen n < 2 khong phai la so nguyen to
        if (n < 2) {
            return false;
        }
        // check so nguyen to khi n >= 2
        long squareRoot = (long) Math.sqrt(n);
        for (int i = 2; i <= squareRoot; i++) {
            if (n % i == 0) {
                return false;
            }
        }
        return true;
    }
    public From() {
        
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textKey = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jmahoa = new javax.swing.JButton();
        jgiaima = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextK = new javax.swing.JTextField();
        jTextM = new javax.swing.JTextField();
        jTextT = new javax.swing.JTextField();
        jTextP = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableA = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableK = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableKP = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableDC = new javax.swing.JTable();
        jButtonChon = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextKP = new javax.swing.JTextField();
        jButtonLMCK = new javax.swing.JButton();
        jButtonLMKP = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        textout = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        fileButton = new javax.swing.JButton();
        fileLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        textKey2 = new javax.swing.JTextField();
        jMahoaFile = new javax.swing.JButton();
        jGiaiMaFile = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jnoidungfile = new javax.swing.JTextField();
        Jketqua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Văn bản (Hệ Hex)");

        jLabel2.setText("Khoá (Hệ Hex)");

        textInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textInputActionPerformed(evt);
            }
        });

        jLabel3.setText("Đầu ra");

        jmahoa.setText("Mã hoá");
        jmahoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmahoaActionPerformed(evt);
            }
        });

        jgiaima.setText("Giải mã");
        jgiaima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jgiaimaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Mã hoá và giải mã văn bản (Text)");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel5.setText("Chia sẻ khoá");

        jLabel6.setText("Khóa cần chi sẻ :");

        jLabel7.setText("Số thành viên dữ khóa :");

        jLabel8.setText("Số thành viên tối thiểu để mở khóa :");

        jLabel9.setText("Giá trị P:");

        jTextP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPActionPerformed(evt);
            }
        });

        jTableA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "i", "ai"
            }
        ));
        jScrollPane1.setViewportView(jTableA);

        jButton3.setText("Chia Sẻ Khóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTableK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Xi", "Pi"
            }
        ));
        jScrollPane2.setViewportView(jTableK);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel10.setText("Khôi phục khoá");

        jButton4.setText("Gửi ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTableKP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Xi", "Pi"
            }
        ));
        jScrollPane3.setViewportView(jTableKP);

        jLabel11.setText("Bảng Mảnh Khóa");

        jTableDC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Xi", "Pi"
            }
        ));
        jScrollPane4.setViewportView(jTableDC);

        jButtonChon.setText("Chọn");
        jButtonChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChonActionPerformed(evt);
            }
        });

        jLabel12.setText("Bảng Mảnh Khóa được chọn");

        jButton5.setText("Khôi Phục Khóa");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel13.setText("Khóa Được Khôi Phục");

        jButtonLMCK.setText("Làm Mới");
        jButtonLMCK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLMCKActionPerformed(evt);
            }
        });

        jButtonLMKP.setText("Làm Mới");
        jButtonLMKP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLMKPActionPerformed(evt);
            }
        });

        textout.setColumns(20);
        textout.setRows(5);
        jScrollPane5.setViewportView(textout);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Mã hoá và giải mã file");

        jLabel15.setText("File");

        fileButton.setText("File...");
        fileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileButtonActionPerformed(evt);
            }
        });

        fileLabel.setText(" ");

        jLabel16.setText("Khoá (Hệ Hex)");

        jMahoaFile.setText("Mã hoá File");
        jMahoaFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMahoaFileActionPerformed(evt);
            }
        });

        jGiaiMaFile.setText("Giải mã File");
        jGiaiMaFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGiaiMaFileActionPerformed(evt);
            }
        });

        jLabel18.setText("Nội dung File:");

        jnoidungfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnoidungfileActionPerformed(evt);
            }
        });

        Jketqua.setText("File Kết quả");
        Jketqua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JketquaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jMahoaFile)
                                .addGap(93, 93, 93)
                                .addComponent(jGiaiMaFile))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(Jketqua))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jnoidungfile, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textKey, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textInput, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                                        .addComponent(jScrollPane5))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(fileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(18, 18, 18)
                                            .addComponent(fileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jmahoa, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(54, 54, 54)
                                            .addComponent(jgiaima, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(textKey2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(24, 24, 24)
                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(38, 38, 38)
                                            .addComponent(jButton4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonLMCK))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel7)
                                                    .addGap(68, 68, 68))
                                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addGap(38, 38, 38)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jTextT, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextM, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextK, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextP, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(37, 37, 37)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(47, 47, 47)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(53, 53, 53)
                                            .addComponent(jButtonChon, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(96, 96, 96)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(26, 26, 26)
                                            .addComponent(jButton5)))
                                    .addGap(38, 38, 38)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonLMKP)
                                        .addComponent(jLabel13)
                                        .addComponent(jTextKP, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(296, 296, 296))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(526, 526, 526)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(jLabel14)))
                        .addGap(186, 186, 186)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)
                                    .addComponent(textInput, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(textKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel5)
                                .addGap(26, 26, 26)
                                .addComponent(jTextK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jTextP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jButton4)
                        .addComponent(jButtonLMCK))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jmahoa)
                        .addComponent(jgiaima)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fileButton)
                            .addComponent(jLabel15)
                            .addComponent(fileLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonChon)
                            .addComponent(jButton5)
                            .addComponent(jButtonLMKP)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextKP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jnoidungfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(textKey2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jMahoaFile)
                            .addComponent(jGiaiMaFile))
                        .addGap(22, 22, 22)
                        .addComponent(Jketqua)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void MaHoa(){
       try{
        
            Khoa = new Khoa(textKey.getText());
            MaHoaDES64 = new DES();
            String kq=MaHoaDES64.ThucHienDESText(Khoa, textInput.getText(), 1);
            textout.setText(String.valueOf(kq));             
       }
       catch(Exception e){
           System.out.print(e);
       }
        
    }
    private void GiaMa(){
        try{
                Khoa = new Khoa(textKey.getText());
                MaHoaDES64 = new DES();
                String kq=MaHoaDES64.ThucHienDESText(Khoa, textInput.getText(), -1);
                textout.setText(String.valueOf(kq));
           
        }            
        catch(Exception e){
           System.out.print(e);
       }
    }
    private boolean kt(int x){
        for(var it:dsdc){
            if(x==it.getXi())
                return false;
        }
        return true;
    }
    public void setTextKey() {
        this.textKey.setText("0123456789ABCDE1");
    }
    private void MaHoaFile(){
       
        try{
            Khoa = new Khoa(textKey2.getText());
            MaHoaDES64 = new DES();
            String kq=MaHoaDES64.ThucHienDESText(Khoa, jnoidungfile.getText(), 1);

            try{
                FileWriter fw = new FileWriter("C:\\Users\\HuChi\\Desktop\\ketqua.txt");
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write(kq);
                bw.close();
                fw.close();
            }
            catch(Exception e){
                
            }
              
        }
        catch(Exception e){
             e.printStackTrace();
        }        
    }
    private void GiaiMaFile(){
       
        try{
            Khoa = new Khoa(textKey2.getText());
            MaHoaDES64 = new DES();
            String kq=MaHoaDES64.ThucHienDESText(Khoa, jnoidungfile.getText(), -1);

            try{
                FileWriter fw = new FileWriter("C:\\Users\\HuChi\\Desktop\\ketqua.txt");
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write(kq);
                bw.close();
                fw.close();
            }
            catch(Exception e){
                
            }
              
        }
        catch(Exception e){
             e.printStackTrace();
        }        
    }
    public void setTextKey2(){
        this.textKey2.setText("0123456789ABCDE1");
    }
    
    private void jmahoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmahoaActionPerformed
        
        try{
            if(textInput.getText().compareToIgnoreCase("")==0){
                JOptionPane.showMessageDialog(null, "Cần nhập văn bản cần giải mã", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{ 
                if(textKey.getText().compareToIgnoreCase("")==0 ){
                  JOptionPane.showMessageDialog(null, "Cần nhập khoá cần giải mã", "Error", JOptionPane.ERROR_MESSAGE);  
                }                    
                else{
                    if(textKey.getText().length()==16){
                        MaHoa();
                    }   
                    else{
                       JOptionPane.showMessageDialog(null, "Khoá phải đủ 16 phần tử", "Error", JOptionPane.ERROR_MESSAGE);  
                    }
                    }     
                
            }
        }    
        catch(Exception ex){ 
        }     
    }//GEN-LAST:event_jmahoaActionPerformed

    private void jgiaimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jgiaimaActionPerformed
        // TODO add your handling code here:
        
        try{
            if(textInput.getText().compareToIgnoreCase("")==0){
                JOptionPane.showMessageDialog(null, "Cần nhập văn bản cần giải mã", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{ 
                
                if(textInput.getText().length()<128){
                    JOptionPane.showMessageDialog(null, "Văn bản cần giải mã chưa đủ phần tử", "Error", JOptionPane.ERROR_MESSAGE);
                }
                else{
                    if(textKey.getText().compareToIgnoreCase("")==0 ){
                      JOptionPane.showMessageDialog(null, "Cần nhập khoá cần giải mã", "Error", JOptionPane.ERROR_MESSAGE);  
                    }                    
                    else{
                        if(textKey.getText().length()==16){
                            
                            GiaMa();
                        }   
                        else{
                           JOptionPane.showMessageDialog(null, "Khoá phải đủ 16 phần tử", "Error", JOptionPane.ERROR_MESSAGE);  
                        }
                    }     
                }
            }
        }    
        catch(Exception ex){ 
        }   
    }//GEN-LAST:event_jgiaimaActionPerformed

    private void jTextPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            if(KtSNT(Long.parseLong(jTextP.getText()))){
                if(Integer.parseInt(jTextP.getText()) <= Integer.parseInt(jTextM.getText())){
                    JOptionPane.showMessageDialog(this,"Số Thành Viên Dữ Khóa Phải nhỏ Hơn P.","Error",JOptionPane.ERROR_MESSAGE);
               }
               else{
                  if(Integer.parseInt(jTextP.getText())>Integer.parseInt(jTextK.getText())){
                      if(Long.parseLong(jTextT.getText()) <= Long.parseLong(jTextM.getText())){
                         ChiSeKhoa chiase=new ChiSeKhoa();
                         ds= chiase.chikhoa(Long.parseLong(jTextK.getText()), Long.parseLong(jTextP.getText()),
                             Long.parseLong(jTextM.getText()), Long.parseLong(jTextT.getText()));
                         ArrayList<Long> sa=chiase.dA;
                         jTableA.setModel(new dsADAO(sa));
                         jTableK.setModel(new ChiaSeKhoaDAO(ds));
                      }else{
                          JOptionPane.showMessageDialog(this,"số thành viến mở khóa không được lớn hơn số thành viên giữ khóa","Error",JOptionPane.ERROR_MESSAGE);
                      }
                  }
                  else{
                      JOptionPane.showMessageDialog(this,"Khóa Phải nhỏ Hơn P.","Error",JOptionPane.ERROR_MESSAGE);
                  }      
                }
            }else{
                JOptionPane.showMessageDialog(this,"P Không Phải Số Nguyên Tố","Error",JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,"Nhập Sai kiểu dữ liệ(Tất cả đều là số nguyên)");
        }
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dsg=ds;
        jTableKP.setModel(new ChiaSeKhoaDAO(dsg));
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChonActionPerformed
        // TODO add your handling code here:
        int dong=-1;
        dong= jTableKP.getSelectedRow();
        if(dong!=-1){
            if(kt(dong+1)){
                DuocChon dc= new DuocChon(dong+1,ds.get(dong));
                dsdc.add(dc);
                jTableDC.setModel(new DuocChonDAO(dsdc));
            }
            else{
                JOptionPane.showMessageDialog(this,"Mảnh đã tồn tại !!!","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonChonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         ChiSeKhoa chiase=new ChiSeKhoa();
         long kq=chiase.khoiphuckhoa(dsdc, Integer.parseInt(jTextP.getText()));
         jTextKP.setText((String.valueOf(kq)));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButtonLMCKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLMCKActionPerformed
        // TODO add your handling code here:
        jTextK.setText("");
        jTextP.setText("");
        jTextM.setText("");
        jTextT.setText("");
        ds.removeAll(ds);
        jTableA.setModel(new dsADAO());
       jTableK.setModel(new ChiaSeKhoaDAO(ds));
    }//GEN-LAST:event_jButtonLMCKActionPerformed

    private void jButtonLMKPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLMKPActionPerformed
        // TODO add your handling code here:
        dsdc.removeAll(dsdc);
        jTableDC.setModel(new DuocChonDAO(dsdc));
        jTextKP.setText("");
        jTableKP.setModel(new ChiaSeKhoaDAO());
    }//GEN-LAST:event_jButtonLMKPActionPerformed

    private void textInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textInputActionPerformed

    private void fileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter textFilter = new FileNameExtensionFilter("Text","txt","docx");
        fileChooser.setFileFilter(textFilter);
        fileChooser.setMultiSelectionEnabled(false);
        fileChooser.setCurrentDirectory(new File("C:\\Users\\HuChi\\Desktop"));
        int x = fileChooser.showDialog(this,"Select");
        if (x==JFileChooser.APPROVE_OPTION){
            File f = fileChooser.getSelectedFile();
            
            fileLabel.setText(f.getName());
            Scanner sc;
            try {
                sc = new Scanner(f);
                jnoidungfile.setText(sc.nextLine());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(From.class.getName()).log(Level.SEVERE, null, ex);
            }           
        }
        
    }//GEN-LAST:event_fileButtonActionPerformed
    
    private void jMahoaFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMahoaFileActionPerformed
        // TODO add your handling code here:
        try{
            if(jnoidungfile.getText().compareToIgnoreCase("")==0){
                JOptionPane.showMessageDialog(null, "Cần chọn file mã hoá", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
                 if(textKey2.getText().compareToIgnoreCase("")==0 ){
                      JOptionPane.showMessageDialog(null, "Cần nhập khoá cần giải mã", "Error", JOptionPane.ERROR_MESSAGE);  
                    }                    
                    else{
                        if(textKey2.getText().length()==16){
                            JOptionPane.showMessageDialog(this,"Đã mã hoá! Xem kết quả trong file Ketqua.txt!","Notification",JOptionPane.INFORMATION_MESSAGE);   
                            MaHoaFile();
                        }   
                        else{
                           JOptionPane.showMessageDialog(null, "Khoá phải đủ 16 phần tử", "Error", JOptionPane.ERROR_MESSAGE);  
                        }
                    }  

            }
        }    
        catch(Exception ex){
            
        }          
    }//GEN-LAST:event_jMahoaFileActionPerformed

    private void jnoidungfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnoidungfileActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jnoidungfileActionPerformed

    private void jGiaiMaFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGiaiMaFileActionPerformed
        // TODO add your handling code here:
        try{
            if(jnoidungfile.getText().compareToIgnoreCase("")==0){
                JOptionPane.showMessageDialog(null, "Cần chọn file mã hoá", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
                 if(textKey2.getText().compareToIgnoreCase("")==0 ){
                      JOptionPane.showMessageDialog(null, "Cần nhập khoá cần giải mã", "Error", JOptionPane.ERROR_MESSAGE);  
                    }                    
                    else{
                        if(textKey2.getText().length()==16){
                            JOptionPane.showMessageDialog(this,"Đã mã hoá! Xem kết quả trong file Ketqua.txt!","Notification",JOptionPane.INFORMATION_MESSAGE);   
                            GiaiMaFile();
                        }   
                        else{
                           JOptionPane.showMessageDialog(null, "Khoá phải đủ 16 phần tử", "Error", JOptionPane.ERROR_MESSAGE);  
                        }
                    }  

            }
        }    
        catch(Exception ex){
            
        }      
    }//GEN-LAST:event_jGiaiMaFileActionPerformed

    private void JketquaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JketquaActionPerformed
       try {
            File file = new File("C:\\Users\\HuChi\\Desktop\\ketqua.txt");
            Desktop dt = Desktop.getDesktop();
            dt.open(file);
        } 
       catch (IOException ex) {
            System.out.print(ex);
        }
    
    }//GEN-LAST:event_JketquaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(From.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new From().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jketqua;
    private javax.swing.JButton fileButton;
    private javax.swing.JLabel fileLabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonChon;
    private javax.swing.JButton jButtonLMCK;
    private javax.swing.JButton jButtonLMKP;
    private javax.swing.JButton jGiaiMaFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jMahoaFile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableA;
    private javax.swing.JTable jTableDC;
    private javax.swing.JTable jTableK;
    private javax.swing.JTable jTableKP;
    private javax.swing.JTextField jTextK;
    private javax.swing.JTextField jTextKP;
    private javax.swing.JTextField jTextM;
    private javax.swing.JTextField jTextP;
    private javax.swing.JTextField jTextT;
    private javax.swing.JButton jgiaima;
    private javax.swing.JButton jmahoa;
    private javax.swing.JTextField jnoidungfile;
    private javax.swing.JTextField textInput;
    private javax.swing.JTextField textKey;
    private javax.swing.JTextField textKey2;
    private javax.swing.JTextArea textout;
    // End of variables declaration//GEN-END:variables
}
